---
title: "COVID-19 Prediciton for Confirmed Cases"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: https://github.com/dspim/COVID-19-Forecasts
    css: "css/styles.css"
---
  
```{r setup, include=FALSE}
list.of.packages <- c("htmlwidgets")
new.packages <- list.of.packages[!("htmlwidgets" %in% installed.packages()[,"Package"])]
if(length(new.packages)){
  remotes::install_github("ramnathv/htmlwidgets", force = TRUE)
} 
library(plotly)
library(tidyr)
library(dplyr)
library(ggplot2)
library(viridisLite)
library(htmlwidgets)
library(dygraphs)
library(DT)
library(sparkline)
library(flexdashboard)

dat1_global <- read.csv("data/Stage1/Stage1_NovelCovid_worldwide.csv", stringsAsFactors = FALSE) 
dat1_tw <- read.csv("data/Stage1/Stage1_NovelCovid_tw.csv", stringsAsFactors = FALSE) 
dat1_tw$date <- as.Date(dat1_tw$date)
dat1_tw_c <- read.csv("data/Stage1/Stage1_Taiwan_CDC.csv", stringsAsFactors = FALSE)
dat1_tw_c$date <- as.Date(dat1_tw_c$date)

dat2_global <- read.csv("data/Stage2/Stage2_worldwide_pred.csv", stringsAsFactors = FALSE) 
dat2_global$date <- as.Date(dat2_global$date)
dat2_tw <- read.csv("data/Stage2/Stage2_tw_pred.csv", stringsAsFactors = FALSE) 
dat2_tw_c <- read.csv("data/Stage2/Stage2_tw_county_pred.csv", stringsAsFactors = FALSE) 
dat2_tw_c$date <- as.Date(dat2_tw_c$date)
tmp <- read.csv("data/Stage2/Stage2_tw_pred_caches.csv", stringsAsFactors = FALSE)
dat2_tw_ <- bind_rows(dat2_tw, tmp) %>% 
  distinct() %>% 
  mutate(date=as.Date(date)) %>% 
  arrange(date)

r <- read.csv("data/country_region.csv", stringsAsFactors = FALSE) %>% 
  rename("country" = "name") %>% 
  select(country, region, sub.region)
# r$country <- r$country %>% tolower()

# now <- Sys.Date()-1
# now <- as.Date("2020-03-26")
now <- max(as.Date(dat2_global$date))
```


Tawian
=====================================  

Row
-----------------------------------------------------------------

### Bias

```{r}
now <- max(as.Date(dat2_tw$date))
true <- dat1_tw$actual_cases[dat1_tw$date == now]
pred <- dat2_tw$predict_cases[dat2_tw$date == (now-1)]
valueBox(paste0(round(pred - true), " cases"), 
         caption = "Yesterday Prediction Errors",
         icon = "fa-ruler")
```

### MAE

```{r}
mae <- 
  dat2_tw_ %>% 
  mutate(error = predict_cases-actual_cases) %>% 
  tail(7) %>%  
  summarise(mae=mean(abs(error), na.rm = TRUE)) %>% "[["("mae")

valueBox(paste0(round(mae, 2), " cases"), 
         caption = "Mean Absolute Prediction Error in last 7 days",
         icon = "fa-ruler")
```

### Growth Factor of Daily New Cases

```{r}
value <- dat1_tw %>% 
  filter(between(as.Date(date), now-2, now)) %>% 
  "[["("actual_cases") %>% diff %>% log %>% diff %>% exp %>% round(3)

valueBox(value, caption = "Growth Factor of Daily New Cases <br><small> (today confiremd cases) / (yesterday confiremd cases) </small>", icon="fa-edit")
# rate <-
#   dat1_tw %>% 
#   mutate(rate=(actual_cases-lag(actual_cases))/actual_cases) %>% 
#   tail(7) %>% 
#   summarise(rate=mean(rate, na.rm = TRUE)) %>% "[["("rate")
# 
# valueBox(paste0(round(100*rate, digits = 2), "%"), 
#          icon = "fa-chart-line")
```

### Growth Rate

```{r}
rate <-
  dat2_tw %>% 
  tail(1) %>% 
  select(-c(country, province, date, actual_cases)) %>% 
  gather(key = "var", value="value") %>% 
  mutate(rate=(value-lag(value))/value) %>% 
  tail(7) %>% 
  summarise(rate=mean(rate, na.rm = TRUE)) %>% "[["("rate")

valueBox(paste0(round(100*rate, digits = 2), "%"), 
         caption="Growth Rate of Daily New Cases in next 7 days",
         icon = "fa-chart-line")
```



Row
-----------------------------------------------------------------

### Total and New Confirmed Cases (Taiwan) {data-width=600}

```{r}
startDate <- as.Date(min(dat1_tw$date))

df <- 
  data.frame(actual=c(dat1_tw$actual_cases, rep(NA, 7)),
             new = c(1, sapply(2:nrow(dat1_tw), function(i){
               dat1_tw$actual_cases[i] - dat1_tw$actual_cases[i-1]
               }), rep(NA, 7)),
             forecast=c(rep(NA, nrow(dat1_tw)-1),
               dat2_tw[dat2_tw$date == now, c(4:11)] %>% unlist() %>% unname())) %>%
  mutate(forecast_new = forecast - lag(forecast)) 

df[["forecast_new"]][dat1_tw$date == now] <- NA

df <- df %>%  ts(start = as.Date(startDate), frequency = 1)
col <- c("#66c2a5", "#c27766", "#6683c2", "#a566c2")

df %>%
  dygraph(ylab = "Cases") %>% 
  dySeries("actual", label = "Total") %>%
  dySeries("forecast", label = "Total (forecasts)", strokePattern = "dashed") %>% 
  dyBarSeries("new", label = "New") %>% 
  dyBarSeries("forecast_new", label="New (forecasts)") %>% 
  dyLegend(labelsSeparateLines = TRUE) %>% 
  dyRangeSelector(dateWindow = c(as.Date(format(now-14)), as.Date(now+7))) %>% 
  dyOptions(colors = col, strokeWidth = 3) 
```


### Daily New Confirmed Cases (Taiwan) {data-width=400}

```{r}
min_value <- min(dat2_tw$actual_cases)
max_value <- max(dat2_tw$predict_cases_7)

df2 <- dat2_tw_ %>%
  mutate(predict_cases=actual_cases) %>% 
  gather(key="key", value="value", -c("country", "province","date","actual_cases")) %>% 
  group_by(country, province, date, actual_cases) %>% 
  summarise(
    forecast_trend = spk_chr(value, type="line", width=125,
                  chartRangeMin=min_value, chartRangeMax=max_value)
  ) %>% ungroup() %>% 
  mutate(new_cases=actual_cases-lag(actual_cases)) %>% 
  mutate(country=as.character(country), 
         # country=factor(country), 
         province=factor(province), 
         date=as.Date(date)) %>% 
  mutate(country=ifelse(country=="taiwan*", "Taiwan", country)) %>% 
  arrange(desc(date)) %>% 
  select(`Country` = country, 
         `Date` = date, 
         `New cases` = new_cases, 
         `Total cases` = actual_cases,
         `Forecasts trend` = forecast_trend)
  
cb <- htmlwidgets::JS('function(){debugger;HTMLWidgets.staticRender();}')

d1 <- datatable(df2, rownames = FALSE, escape = FALSE,
                options = list(dom = "t", paging = FALSE, fnDrawCallback=cb))
spk_add_deps(d1)
```

Global
=====================================  
```{r}
startDate <- as.Date(min(dat1_global$date))
now <- max(as.Date(dat1_global$date))

dat1_global_ <- dat1_global %>% 
  mutate(date=as.Date(date)) %>% 
  group_by(country, date) %>% 
  summarise(actual_cases=sum(actual_cases, na.rm = TRUE)) %>% 
  ungroup() %>% 
  left_join(r, by="country")

dat_region <- dat1_global_ %>%
  select(date, sub.region, actual_cases) %>% 
  group_by(date, sub.region) %>% 
  summarise(actual_cases = sum(actual_cases, na.rm = TRUE))
#-------------------------------------------------
dat2_global_ <- dat2_global %>% 
  mutate(date=as.Date(date),
         lower_country = tolower(country)) %>% 
  filter(date == now) %>% 
  group_by(lower_country, date) %>% 
  summarise(actual_cases=sum(actual_cases, na.rm = TRUE),
            predict_cases=sum(predict_cases, na.rm = TRUE),
            predict_cases_2=sum(predict_cases_2, na.rm = TRUE),
            predict_cases_3=sum(predict_cases_3, na.rm = TRUE),
            predict_cases_4=sum(predict_cases_4, na.rm = TRUE),
            predict_cases_5=sum(predict_cases_5, na.rm = TRUE),
            predict_cases_6=sum(predict_cases_6, na.rm = TRUE),
            predict_cases_7=sum(predict_cases_7, na.rm = TRUE)) %>% 
  ungroup() %>% 
  left_join(mutate(r, lower_country = tolower(country)),
            by=c("lower_country"))

dat2_global_ <- dat2_global_ %>% 
  select(-lower_country) %>% 
  gather(type, n, -date, -country, -region, -sub.region)
dat2_global_$date[dat2_global_$type == "predict_cases"] <- now + 1
dat2_global_$date[dat2_global_$type == "predict_cases_2"] <- now + 2
dat2_global_$date[dat2_global_$type == "predict_cases_3"] <- now + 3
dat2_global_$date[dat2_global_$type == "predict_cases_4"] <- now + 4
dat2_global_$date[dat2_global_$type == "predict_cases_5"] <- now + 5
dat2_global_$date[dat2_global_$type == "predict_cases_6"] <- now + 6
dat2_global_$date[dat2_global_$type == "predict_cases_7"] <- now + 7

dat2_global_ <- dat2_global_ %>% 
  filter(type != "actual_cases") %>% 
  select(date, sub.region, n)
#------------------------------------------------

lab <- dat_region %>% 
  filter(date==now) %>% 
  arrange(desc(actual_cases)) %>% 
  "[["("sub.region")

dat_region$sub.region <- factor(dat_region$sub.region, lab)
```

Row
-----------------------------------------------------------------
### Total confirmed cases
```{r}
value <- dat_region %>% 
  filter(date==now) %>% 
  "[["("actual_cases") %>% sum(na.rm = TRUE)

value <- format(value, big.mark=",", scientific=FALSE)
valueBox(value, caption = "Total Cases", icon="fa-upload")
```

### New confirmed cases
```{r}
value <- dat_region %>% 
  filter(between(date, now-1, now)) %>%
  group_by(date) %>% 
  summarise(actual_cases=sum(actual_cases, na.rm = TRUE)) %>% 
  "[["("actual_cases") %>% diff

value <- format(value, big.mark=",", scientific=FALSE)

valueBox(value, caption = "New Cases", icon="fa-upload")
```

### Growth Factor of Daily New Cases
```{r}
value <- dat_region %>% 
  filter(between(date, now-2, now)) %>%
  group_by(date) %>% 
  summarise(actual_cases=sum(actual_cases, na.rm = TRUE)) %>% 
  "[["("actual_cases") %>% diff %>% log %>% diff %>% exp %>% round(3)

valueBox(value, caption = "Growth Factor of Daily New Cases <br><small> (today confiremd cases) / (yesterday confiremd cases) </small>", icon="fa-edit")
```

### Number of Countries
```{r}
value <- dat1_global_ %>% 
  filter(date==now) %>%
  summarise(count=sum(country>0)) %>% "[["("count")

value <- format(value, big.mark=",", scientific=FALSE)

valueBox(value, caption = "Number of Countries", icon="fa-flag")
```

Row
-----------------------------------------------------------------

### Total and New Confirmed Cases (Worldwide) {data-width=600}

```{r}
tmp <- dat_region %>% rename("n" = "actual_cases") %>% 
  ungroup()
p <- rbind(tmp, dat2_global_) %>% 
  group_by(date, sub.region) %>% 
  summarise(n = sum(n)) %>% 
  mutate(`Total cases (log10 scale)` = round(log10(n+1),3)) %>% 
  ungroup() %>% 
  na.omit() %>% 
  rename(`Date` = date, `Sub region` = sub.region) %>% 
  # View()
  ggplot(., aes(x=`Date`, y=`Total cases (log10 scale)`, fill=`Sub region`)) +
  # geom_line(aes(color = sub.region))
  geom_area(position = 'stack') +
  scale_x_date() +
  labs(x="Date",
       y="Cumulative number of confirmed cases \n(Logarithmic scale)",
       fill="Sub Region") +
  scale_fill_viridis_d() +
  geom_vline(aes(xintercept = now), color = "#020728", size=1.5)

ggplotly(p)

```

### Daily New Confirmed Cases (Worldwide) {data-width=400}

```{r}
# min_value <- min(dat2_global$actual_cases)
# max_value <- max(dat2_global$predict_cases_7)

dat1_global_ <- dat1_global %>% 
  mutate(date=as.Date(date)) %>% 
  group_by(country, date) %>% 
  summarise_if(is.numeric, sum, na.rm = TRUE) %>% 
  ungroup() %>% 
  left_join(r, by="country")

tab <- dat1_global_ %>%
  mutate(country=country,
         region=factor(region),
         sub.region=factor(sub.region, lab),
         date=as.Date(date)) %>%
  arrange(country, date) %>% 
  group_by(country) %>% 
  mutate(new_cases=actual_cases-lag(actual_cases)) %>%
  mutate(growth_factor=round(new_cases/lag(new_cases+1),3)) %>%
  mutate(growth_factor=ifelse(growth_factor<0, 0, growth_factor)) %>%
  filter(date==now) %>%
  arrange(sub.region, desc(actual_cases)) %>%
  select(`Country` = country,
         #`Region` = region,
         `Sub region` = sub.region,
         `Date` = date,
         `Total cases` = actual_cases,
         `New cases` = new_cases,
         `Growth factor` = growth_factor
         )

datatable(tab, rownames = FALSE, escape = FALSE,
          options = list(dom = "t", paging = FALSE))
```